import "reflect-metadata";
import { Container } from "inversify";
import { JwtService } from "./features/auth/adapters/jwt-service";
import { Argon2Service } from "./features/auth/adapters/argon2-service";
import { NodemailerService } from "./features/auth/adapters/email-service/nodemailer-service";
import { UserRepository } from "./features/users/repositories/user-repository-mongodb";
import { UserQueryRepository } from "./features/users/repositories/user-query-repository-mongodb";
import { BlogsRepository } from "./features/blogs/repositories/blogs.mongodb.repositories";
import { BlogsQueryRepository } from "./features/blogs/repositories/blogs.query-mongodb.repositories";
import { PostsRepository } from "./features/posts/repositories/posts.mongodb.repositories";
import { PostsQueryRepository } from "./features/posts/repositories/posts.mongodb-query-repository";
import { CommentsRepository } from "./features/comments/repositories/commentsRepository";
import { CommentsQueryRepository } from "./features/comments/repositories/commentsQueryRepository";
import { DeviceRepository } from "./features/security/repository/device-repository";
import { UserService } from "./features/users/application/command-services/user-service";
import { BlogsService } from "./features/blogs/application/command-services/blogs-services";
import { PostsService } from "./features/posts/application/command-services/posts-services";
import { CommentService } from "./features/comments/application/command-service/comment-service";
import { AuthService } from "./features/auth/application/command-services/auth-service";
import { CreateBlogHandler } from "./features/blogs/routers/handlers/create-blog.handler";
import { CreatePostForSpecificId } from "./features/blogs/routers/handlers/create-post-for-specific-id";
import { DeleteBlogHandler } from "./features/blogs/routers/handlers/delete-blog.handler";
import { GetAllBlogsHandler } from "./features/blogs/routers/handlers/get-all-blogs.handler";
import { GetBlogByIdHandler } from "./features/blogs/routers/handlers/get-by-id.handler";
import { UpdateBlogHandler } from "./features/blogs/routers/handlers/update-blog.handler";
import { GetAllPostsForSpecificBlogIdHandler } from "./features/blogs/routers/handlers/get-all-posts-for-specific-blog-id";
import { LoginAuthHandler } from "./features/auth/routers/handlers/login-auth-handler";
import { LogoutHandler } from "./features/auth/routers/handlers/logout-handler";
import { MeAuthHandler } from "./features/auth/routers/handlers/me-auth-handler";
import { NewPasswordHandler } from "./features/auth/routers/handlers/new-password-handler";
import { PasswordRecoveryHandler } from "./features/auth/routers/handlers/password-recovery-handler";
import { RefreshTokenHandler } from "./features/auth/routers/handlers/refresh-token-handler";
import { RegistrationAuthHandler } from "./features/auth/routers/handlers/registration-auth-handler";
import { RegistrationConfirmationHandler } from "./features/auth/routers/handlers/registration-confirmation-handler";
import { RegistrationEmailResendingHandler } from "./features/auth/routers/handlers/registration-email-resending-handler";
import { CreateCommentHandler } from "./features/posts/routers/handlers/create-comment-by-postId";
import { CreatePostHandler } from "./features/posts/routers/handlers/create-post.handler";
import { DeletePostHandler } from "./features/posts/routers/handlers/delete-post.handler";
import { GetAllPostsHandler } from "./features/posts/routers/handlers/get-all-posts.handler";
import { GetCommentsForPostIdHandler } from "./features/posts/routers/handlers/get-comments-for-post-id-handler";
import { GetPostByIdHandler } from "./features/posts/routers/handlers/get-post-by-id.handler";
import { UpdatePostHandler } from "./features/posts/routers/handlers/update-post.handler";
import { DeleteCommentByIdHandler } from "./features/comments/routers/handlers/delete-comment-by-id-handler";
import { GetCommentByIdHandler } from "./features/comments/routers/handlers/get-comment-by-id-handler";
import { UpdateCommentByIdHandler } from "./features/comments/routers/handlers/update-comment-by-id-handler";
import { DeleteAllDevicesHandler } from "./features/security/routers/handlers/delete-all-devices-handler";
import { DeleteDeivceHandler } from "./features/security/routers/handlers/delete-deivce-handler";
import { GetAllActiveDevicesHandler } from "./features/security/routers/handlers/get-all-active-devices-handler";
import { CreateUserHandler } from "./features/users/routers/handlers/create-user-handler";
import { DeleteUserHandler } from "./features/users/routers/handlers/delete-user-handler";
import { GetAllUsersHandler } from "./features/users/routers/handlers/get-all-users-handler";
import { GetUserHandler } from "./features/users/routers/handlers/get-user-handler";
import { CommentsLikesRepository } from "./features/comments/repositories/commentsLikesRepository";
import { Setter } from "date-fns/parse/_lib/Setter";
import { SetLikeForCommentHandler } from "./features/comments/routers/handlers/set-like-for-comment-handler";

export const container = new Container();

// Adapters
container.bind(JwtService).toSelf().inSingletonScope();
container.bind(Argon2Service).toSelf().inSingletonScope();
container.bind(NodemailerService).toSelf().inSingletonScope();

// Repositories
container.bind(UserRepository).toSelf().inSingletonScope();
container.bind(UserQueryRepository).toSelf().inSingletonScope();
container.bind(BlogsRepository).toSelf().inSingletonScope();
container.bind(BlogsQueryRepository).toSelf().inSingletonScope();
container.bind(PostsRepository).toSelf().inSingletonScope();
container.bind(PostsQueryRepository).toSelf().inSingletonScope();
container.bind(CommentsRepository).toSelf().inSingletonScope();
container.bind(CommentsLikesRepository).toSelf().inSingletonScope();
container.bind(CommentsQueryRepository).toSelf().inSingletonScope();
container.bind(DeviceRepository).toSelf().inSingletonScope();

// Services
container.bind(UserService).toSelf().inSingletonScope();
container.bind(BlogsService).toSelf().inSingletonScope();
container.bind(PostsService).toSelf().inSingletonScope();
container.bind(CommentService).toSelf().inSingletonScope();
container.bind(AuthService).toSelf().inSingletonScope();

//Handlers

container.bind(CreateBlogHandler).toSelf().inSingletonScope();
container.bind(CreatePostForSpecificId).toSelf().inSingletonScope();
container.bind(DeleteBlogHandler).toSelf().inSingletonScope();
container.bind(GetAllBlogsHandler).toSelf().inSingletonScope();
container.bind(GetBlogByIdHandler).toSelf().inSingletonScope();
container.bind(UpdateBlogHandler).toSelf().inSingletonScope();
container.bind(GetAllPostsForSpecificBlogIdHandler).toSelf().inSingletonScope();
container.bind(LoginAuthHandler).toSelf().inSingletonScope();
container.bind(LogoutHandler).toSelf().inSingletonScope();
container.bind(MeAuthHandler).toSelf().inSingletonScope();
container.bind(NewPasswordHandler).toSelf().inSingletonScope();
container.bind(PasswordRecoveryHandler).toSelf().inSingletonScope();
container.bind(RefreshTokenHandler).toSelf().inSingletonScope();
container.bind(RegistrationAuthHandler).toSelf().inSingletonScope();
container.bind(RegistrationConfirmationHandler).toSelf().inSingletonScope();
container.bind(RegistrationEmailResendingHandler).toSelf().inSingletonScope();
container.bind(CreateCommentHandler).toSelf().inSingletonScope();
container.bind(CreatePostHandler).toSelf().inSingletonScope();
container.bind(DeletePostHandler).toSelf().inSingletonScope();
container.bind(GetAllPostsHandler).toSelf().inSingletonScope();
container.bind(GetCommentsForPostIdHandler).toSelf().inSingletonScope();
container.bind(GetPostByIdHandler).toSelf().inSingletonScope();
container.bind(UpdatePostHandler).toSelf().inSingletonScope();
container.bind(DeleteCommentByIdHandler).toSelf().inSingletonScope();
container.bind(GetCommentByIdHandler).toSelf().inSingletonScope();
container.bind(UpdateCommentByIdHandler).toSelf().inSingletonScope();
container.bind(DeleteAllDevicesHandler).toSelf().inSingletonScope();
container.bind(DeleteDeivceHandler).toSelf().inSingletonScope();
container.bind(GetAllActiveDevicesHandler).toSelf().inSingletonScope();
container.bind(CreateUserHandler).toSelf().inSingletonScope();
container.bind(DeleteUserHandler).toSelf().inSingletonScope();
container.bind(GetAllUsersHandler).toSelf().inSingletonScope();
container.bind(GetUserHandler).toSelf().inSingletonScope();
container.bind(SetLikeForCommentHandler).toSelf().inSingletonScope();
